# COMSOL 6.4 batch configuration with a larger Java heap for Stage 576n.
batch
-startup
D:\Program Files\COMSOL\COMSOL64\Multiphysics\plugins\org.eclipse.equinox.launcher_1.7.0.v20250519-0528.jar
--launcher.library
D:\Program Files\COMSOL\COMSOL64\Multiphysics\bin\win64
-vm
D:\Program Files\COMSOL\COMSOL64\Multiphysics\java\win64\jre\bin\server\jvm.dll
-vmargs
-Djdk.lang.Process.allowAmbiguousCommands=false
-Declipse.product=com.comsol.util.product
-Dosgi.bundles=org.eclipse.update.configurator@1:start,org.eclipse.equinox.common@2:start,org.apache.felix.scr@1:start,org.eclipse.equinox.event@3:start,org.eclipse.core.runtime@start
-Dosgi.bundles.defaultStartLevel=4
-Dosgi.startLevel=6
-Dosgi.clean=true
-Dorg.osgi.service.log.admin.loglevel=INFO
-Dosgi.locking=none
-Dosgi.configuration.area=@user.home/.comsol/v64/configuration/comsol_@process.id
-Dosgi.instance.area=@user.home/.comsol/v64/workspace/comsol_@process.id
-Dosgi.checkConfiguration=true
-Dcs.logoutput=file
-Dcs.logfileprefix=batch
-Dcs.uniqueworkspace=on
-Dcs.processuid=@process.id
-Xss4m
-Xms512m
-Xmx9g
-XX:MaxMetaspaceSize=1g
-Dlog4j2.formatMsgNoLookups=true
-Djavax.net.ssl.trustStoreType=Windows-ROOT
